import Head from 'next/head'
import Image from 'next/image'
//import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import styled from '../styles/home.module.sass'
//import Returnstatus from "@/status/store";
// fixed error...
import CreateAccount from "@/pages/account";
import {useEffect} from "react";

export default function Home() {
    const Devmode = () => {
            if (process.env.NODE_ENV === "development") {
                return (
                    <p> development mode </p>
                )
            } else {
                return (
                    <p> development mode </p>
                )
            }
        }
  return (
    <div className={styled.container}>
      <Head>
        <title>V : {process.env.NODE_ENV} mode</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
              <Image
                src="/image.jpg"
                alt= "Logo"
                className={styles.vercelLogo}
                width={500}
                height={500}
                priority
              />
			<p>insert code is : {'  {process.env.NODE_ENV}'}.</p>
			<p>How to insert code is edit index.tsx</p>
          <CreateAccount />
          <Devmode/>
      </main>
    </div>
  )
}
